/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Jtheberg Documentation",
  "tagline": "Documentation complète",
  "favicon": "img/favicon.ico",
  "url": "https://jtheberg.cloud",
  "baseUrl": "/",
  "stylesheets": [
    "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css",
    "https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap"
  ],
  "organizationName": "Jtheberg-hebergeur",
  "projectName": "Docs-WebSite",
  "deploymentBranch": "gh-pages",
  "trailingSlash": false,
  "onBrokenLinks": "throw",
  "markdown": {
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    },
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "i18n": {
    "defaultLocale": "fr",
    "locales": [
      "fr"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.js",
          "editUrl": "https://github.com/Jtheberg-hebergeur/Docs-WebSite/edit/Public/",
          "showLastUpdateAuthor": false,
          "showLastUpdateTime": false,
          "routeBasePath": "/",
          "breadcrumbs": true,
          "beforeDefaultRemarkPlugins": [],
          "remarkPlugins": [],
          "rehypePlugins": []
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "onBrokenLinks": "throw",
    "onBrokenMarkdownLinks": "warn",
    "docs": {
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      },
      "versionPersistence": "localStorage"
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "image": "img/docusaurus-social-card.jpg",
    "navbar": {
      "title": "Jtheberg",
      "logo": {
        "alt": "Jtheberg Logo",
        "src": "https://jtheberg.cloud/assets/images/logo.png"
      },
      "hideOnScroll": false,
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "📚 Documentation"
        },
        {
          "href": "https://jtheberg.cloud",
          "label": "🏠 Site Principal",
          "position": "left"
        },
        {
          "href": "https://jtheberg.cloud/contact",
          "label": "📞 Contact",
          "position": "left"
        },
        {
          "to": "/contributors",
          "label": "👥 Contributeurs",
          "position": "left"
        }
      ]
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "📚 Documentation",
          "items": [
            {
              "label": "Introduction",
              "to": "/docs/intro"
            },
            {
              "label": "Pterodactyl",
              "to": "/docs/pterodactyl/installer-pterodactyl"
            },
            {
              "label": "Docker",
              "to": "/docs/docker/quest-ce-que-docker"
            },
            {
              "label": "Plesk",
              "to": "/docs/plesk/installer-plesk"
            }
          ]
        },
        {
          "title": "🌐 Jtheberg",
          "items": [
            {
              "label": "Site Principal",
              "href": "https://jtheberg.cloud"
            },
            {
              "label": "VPS",
              "href": "https://jtheberg.cloud/hosting/vps"
            },
            {
              "label": "Hébergement Web",
              "href": "https://jtheberg.cloud/hosting/web"
            },
            {
              "label": "Minecraft",
              "href": "https://jtheberg.cloud/hosting/minecraft"
            }
          ]
        },
        {
          "title": "💬 Communauté",
          "items": [
            {
              "label": "Contact",
              "href": "https://jtheberg.cloud/contact"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/KizYTB"
            },
            {
              "label": "Trustpilot",
              "href": "https://www.trustpilot.com/review/jtheberg.cloud"
            }
          ]
        },
        {
          "title": "🔧 Support",
          "items": [
            {
              "label": "Licenses",
              "href": "https://jtheberg.cloud/licenses"
            },
            {
              "label": "Status",
              "href": "https://status.jtheberg.cloud"
            }
          ]
        }
      ],
      "copyright": "\n          <div style=\"margin-top: 2rem; padding-top: 2rem; border-top: 1px solid rgba(255,255,255,0.1);\">\n            <p style=\"margin-bottom: 0.5rem;\">🚀 <strong>Jtheberg</strong> - Hébergeur Web Professionnel</p>\n            <p style=\"margin-bottom: 0.5rem;\">Copyright © 2025 Jtheberg.cloud - Maintenu avec ❤️ par <a href=\"https://github.com/KizYTB\" target=\"_blank\" rel=\"noopener noreferrer\">Kiz___</a></p>\n            <p style=\"font-size: 0.9rem; opacity: 0.8;\">🔒 Sécurité | ⚡ Performance | 📞 Support 24/7</p>\n          </div>\n        "
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#000000",
          "backgroundColor": "#ffffff"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(0, 128, 0)"
            }
          },
          {
            "types": [
              "builtin"
            ],
            "style": {
              "color": "rgb(0, 112, 193)"
            }
          },
          {
            "types": [
              "number",
              "variable",
              "inserted"
            ],
            "style": {
              "color": "rgb(9, 134, 88)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(0, 0, 0)"
            }
          },
          {
            "types": [
              "constant",
              "char"
            ],
            "style": {
              "color": "rgb(129, 31, 63)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "rgb(128, 0, 0)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 0, 0)"
            }
          },
          {
            "types": [
              "deleted",
              "string"
            ],
            "style": {
              "color": "rgb(163, 21, 21)"
            }
          },
          {
            "types": [
              "changed",
              "punctuation"
            ],
            "style": {
              "color": "rgb(4, 81, 165)"
            }
          },
          {
            "types": [
              "function",
              "keyword"
            ],
            "style": {
              "color": "rgb(0, 0, 255)"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(38, 127, 153)"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#9CDCFE",
          "backgroundColor": "#1E1E1E"
        },
        "styles": [
          {
            "types": [
              "prolog"
            ],
            "style": {
              "color": "rgb(0, 0, 128)"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(106, 153, 85)"
            }
          },
          {
            "types": [
              "builtin",
              "changed",
              "keyword",
              "interpolation-punctuation"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "number",
              "inserted"
            ],
            "style": {
              "color": "rgb(181, 206, 168)"
            }
          },
          {
            "types": [
              "constant"
            ],
            "style": {
              "color": "rgb(100, 102, 149)"
            }
          },
          {
            "types": [
              "attr-name",
              "variable"
            ],
            "style": {
              "color": "rgb(156, 220, 254)"
            }
          },
          {
            "types": [
              "deleted",
              "string",
              "attr-value",
              "template-punctuation"
            ],
            "style": {
              "color": "rgb(206, 145, 120)"
            }
          },
          {
            "types": [
              "selector"
            ],
            "style": {
              "color": "rgb(215, 186, 125)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "tag"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "rgb(86, 156, 214)"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "rgb(212, 212, 212)"
            }
          },
          {
            "types": [
              "punctuation"
            ],
            "languages": [
              "markup"
            ],
            "style": {
              "color": "#808080"
            }
          },
          {
            "types": [
              "function"
            ],
            "style": {
              "color": "rgb(220, 220, 170)"
            }
          },
          {
            "types": [
              "class-name"
            ],
            "style": {
              "color": "rgb(78, 201, 176)"
            }
          },
          {
            "types": [
              "char"
            ],
            "style": {
              "color": "rgb(209, 105, 105)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "bash",
        "docker",
        "yaml",
        "json",
        "nginx",
        "php",
        "sql",
        "powershell"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        },
        {
          "className": "code-block-error-line",
          "line": "This will error"
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 5
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "metadata": []
  },
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
